services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  app:
    image: ocelmo/lab3
    container_name: app
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongodb:27017/mydatabase
    ports:
      - "8080:3000"

volumes:
  mongodata:
